# Perform "exit 1" if PR title starts with "WIP" to block accidental merges
name: Check "WIP" in PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check WIP in PR Title
        env:
          # will match any PR title starting with WIP:
          MATCH: "^WIP"
        run: |
          # case-insensitive
          shopt -s nocasematch

          if [[ "${{ github.event.pull_request.title }}" =~ ${MATCH} ]]; then
              echo "::error::PR marked as work in progress"
              exit 1
          fi

          # unset nocasematch option
          shopt -u nocasematch